"""empty message

Revision ID: 054c8f63c6b6
Revises: e5d6fc19da89
Create Date: 2023-03-02 11:59:37.131696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054c8f63c6b6'
down_revision = 'e5d6fc19da89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_products', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_products', 'image')
    # ### end Alembic commands ###
