"""empty message

Revision ID: 09aa158480af
Revises: 29d498624f7b
Create Date: 2023-01-04 09:57:04.972274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09aa158480af'
down_revision = '29d498624f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_auth', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_auth')
    # ### end Alembic commands ###
