"""empty message

Revision ID: 29d498624f7b
Revises: bc4d49ba278d
Create Date: 2022-12-23 23:18:32.638083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29d498624f7b'
down_revision = 'bc4d49ba278d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_index('password', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'users', ['password'], unique=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
