"""empty message

Revision ID: daba4b28666d
Revises: 3fa474b4b819
Create Date: 2023-03-02 11:02:30.189344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'daba4b28666d'
down_revision = '3fa474b4b819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['shopping_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('name', table_name='shopping')
    op.drop_table('shopping')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('rating', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['shopping_categories.id'], name='shopping_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'shopping', ['name'], unique=False)
    op.drop_table('products')
    # ### end Alembic commands ###
